# replit.toml

[unit]
# Command to run your Flask app
command = "python3 app.py"

[env]
# Flask must run on 0.0.0.0 and use Replit's PORT environment variable
FLASK_RUN_HOST = "0.0.0.0"
FLASK_RUN_PORT = "$PORT"

[packager.pip]
# List the Python packages your app needs
packages = [
    "flask",
    "requests"   # Add any other packages your app uses
]
